# -*- coding: utf-8 -*-
from setuptools import find_packages, setup

setup(
    name="samri",
    version="0.0.1",
    description="SAMRI: Segment Anything Model for MRI — decoder-only fine-tuning on precomputed MRI embeddings.",
    long_description=open("README.md", encoding="utf-8").read() if __import__("os").path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    author="Zhao Wang",
    author_email="zhao.wang1@uq.edu.au",
    url="https://github.com/zhaowangmxy/SAMRI",
    license="Apache-2.0",
    packages=find_packages(exclude=("notebooks", "tests", "docs", "examples")),
    python_requires=">=3.10",
    install_requires=[
        "numpy==1.26.4",
        "scipy==1.13.0",
        "scikit-image==0.25.0",
        "scikit-learn",
        "nibabel",
        "SimpleITK>=2.2.1",
        "opencv-python==4.10",
        "matplotlib",
        "tqdm",
        "pandas",
        "einops",
        "h5py",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Operating System :: OS Independent",
    ],
    keywords=["MRI", "segmentation", "medical-imaging", "deep-learning", "SAM"],
)
